---
- name: Gather facts about VMs and ensure google-osconfig-agent is installed
  hosts: "{{ targets }}"
  become: true
  tasks:
    - name: Gather distribution and version facts
      setup:
        filter:
          - ansible_distribution
          - ansible_distribution_version

    - name: Display distribution
      debug:
        var: ansible_distribution

    - name: Display distribution version
      debug:
        var: ansible_distribution_version

    - name: Check if google-osconfig-agent service exists
      shell: systemctl status google-osconfig-agent
      register: systemctl_check
      failed_when: "'Loaded: not-found' in systemctl_check.stdout or 'could not be found' in systemctl_check.stderr"

    - name: Display whether google-osconfig-agent service exists
      debug:
        var: systemctl_check.stdout_lines

    - name: Update apt cache and install google-osconfig-agent
      when: "'Loaded: not-found' in systemctl_check.stdout or 'could not be found' in systemctl_check.stderr"
      apt:
        name: google-osconfig-agent
        update_cache: yes
        state: present

    - name: Get google-osconfig-agent status
      when: "'Loaded: loaded' in systemctl_check.stdout"
      shell: systemctl status google-osconfig-agent
      register: systemctl_output

    - name: Display google-osconfig-agent status
      when: "'Loaded: loaded' in systemctl_check.stdout"
      debug:
        var: systemctl_output.stdout_lines
...
