---
- name: Update apt configuration for google-compute-engine
  hosts: "{{ targets }}"
  become: yes
  tasks:
    - name: Ensure the apt configuration for google-compute-engine is up to date
      copy:
        dest: /etc/apt/sources.list.d/google-compute-engine.list
        content: |
          deb http://packages.cloud.google.com/apt google-compute-engine-stretch-stable main
        owner: root
        group: root
        mode: '0644'

    - name: Update the apt cache
      apt:
        update_cache: yes
...
